version: '3.4'

services:
  searchapi:
    image: ${DOCKER_REGISTRY}searchapi
    build:
      context: .
      dockerfile: SearchAPI/Dockerfile
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"